---
title: "Analysis and Visualization"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_bw() + theme(legend.position = "bottom"))

```


```{r}
# honey bee population for country by year
clean_bee_data %>%
   mutate(year = as.numeric(year)) %>%
   group_by(year) %>%
   summarise(n = sum(honey_producing_colonies)) %>%
   ggplot(aes(x = year, y = n)) + 
   geom_point() + 
   geom_smooth(se = FALSE) +
   theme(axis.text.x = element_text(angle = 90)) +
   labs(
     title = "Honey Bee Colony Count in the US",
     x = "Year",
     y = "Honey Bee Colonies Across the US") +
   scale_x_continuous(
      breaks = c(2002, 2007, 2012, 2017))
```

```{r}
bee_county %>%
   mutate(colony_count = as.numeric(colony_count)) %>%
   drop_na(colony_count) %>%
   group_by(year) %>%
   summarise(n = sum(colony_count)) %>%
   ggplot(aes(x = year, y = n)) + 
   geom_point() + 
   geom_smooth() +
     theme(axis.text.x = element_text(angle = 90)) +
   labs(
     title = "Bee Colony Count in the US",
      x = "Year",
     y = "Bee Colonies Across the US") + 
   scale_x_continuous(
      breaks = c(2002, 2007, 2012))
```

```{r}
top_pesticides %>%
  group_by(compound, year) %>%
   na.omit(epest_high_kg) %>%
   summarise(n = sum(epest_high_kg)) %>%
   ggplot(aes(x = year, y = n, color = compound)) + 
   geom_point() + 
   geom_smooth(se = FALSE) +
     theme(axis.text.x = element_text(angle = 90)) +
     labs(
     title = "Pesticide Use in the US",
     x = "Year",
     y = "Weight of Pesticide used in the US (kg)"
   )

clean_bee_data %>%
  group_by(year) %>%
  summarise(n = sum(honey_producing_colonies)) %>%
  ggplot(aes(x = year, y = n)) + 
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
    title = "Honey Bee Colony Count in the US",
    x = "Year",
    y = "Honey Bee Colonies Across the US"
  )

```

```{r}
# high range of pesticide use
 top_pesticides %>%
   group_by(year) %>%
   na.omit(epest_high_kg) %>%
   summarise(n = sum(epest_high_kg)) %>%
   ggplot(aes(x = year, y = n)) + 
   geom_point() + 
   geom_smooth(se = FALSE) +
     theme(axis.text.x = element_text(angle = 90)) +
    theme(axis.text.x = element_text(angle = 90)) +
       labs(
     title = "Pesticide Use in the US",
     x = "Year",
     y = "Weight of Pesticide used in the US (kg)"
   )

 #low range of pesticide use
 top_pesticides %>%
   group_by(year) %>%
   na.omit(epest_low_kg) %>%
   summarise(n = sum(epest_low_kg)) %>%
   ggplot(aes(x = year, y = n)) + 
   geom_point() + 
   geom_smooth(se = FALSE) +
     theme(axis.text.x = element_text(angle = 90)) +
     theme(axis.text.x = element_text(angle = 90)) +
       labs(
     title = "Pesticide Use in the US",
     x = "Year",
     y = "Weight of Pesticide used in the US (kg)"
   )
```


```{r}
library(maps)

map(database = "United States")

```

```{r}
library(choroplethr)
library(choroplethrAdmin1)

get_admin1_regions("united states of america")

```

```{r}
<<<<<<< HEAD
# state and pesticide
merged_state_data %>%
  mutate(year = as.numeric(year.x)) %>%
  group_by(year, compound) %>%
  summarise(colonies = sum(honey_producing_colonies), 
            pesticides = sum(high)) %>%
  ggplot(aes(x = year, y = pesticides, color = compound) + 
  geom_point() + 
  geom_smooth(se = FALSE) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
    title = "Honey Bee Colony Count in the US",
    x = "Year",
    y = "Honey Bee Colonies Across the US")
```

=======
us_counties = map_data("county") %>%
  

p =   ggplot(data = us_counties,
            mapping = aes(x = long, y = lat,
                          group = group, fill = region))

p2 = p + geom_polygon(color = "gray90", size = 0.1) +
    coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
    guides(fill = FALSE)

p2
```

