
## Pesticide Use and Bee Colonies in the United States

_Background_  
------------------------------------------------------
Exposure to insecticides can make bees more susceptible to pathogens as pesticides suppress their immune systems; studies suggest that this pesticide-pathogen interaction may be driving bees’ widespread collapse in the U.S. over recent decades (Sánchez-Bayo et al. 2016).

Nosema ceranae, a gut microsporidian that can infect bees and has contributed to widespread bee decline, was first found in the U.S. around the same time that neonicotinoids were introduced (Sánchez-Bayo et al. 2016). When bees infected with Nosema are exposed to imidacloprid, a neonicotinoid, they cannot sterilize the colony so the pathogen spreads within the colony (Sánchez-Bayo et al. 2016). Additionally, bees infected with N. ceranae that are exposed to another neonicotinoid, thiacloprid, or the phenyl-pyrazole, fripronil, have higher mortality than non-exposed bees (Sánchez-Bayo et al. 2016). Fipronil and imidacloprid suppress immunity-related genes in honey bees, leading to higher mortality rates for hives infected with Nosema (Sánchez-Bayo et al. 2016). There is a known mechanism of action for immune suppression for neonicotinoids, specifically clothianidin and imidacloprid (Di Prisco et al., 2013).

A survey of pesticides applied to agricultural areas in southern U.S. row crops reported neonicotinoid seed treatments using clothianidin, imidacloprid, and thiacloprid in the high agriculture survey area, in 2014 and 2015 growing seasons (Zawislak et al. 2019). The distribution of foliar applied pesticides in the high-agriculture survey area included chlorpyrifos and clothianidin, among others. Pesticide residues detected in hive products include chlorothalonil and chlorpyrifos (Zawislak et al. 2019). A migratory beekeeper study from Florida to Main was collected after the colony collapse disorder erupted in 2007, with colonies sampled after each stop along the route (Frazier et al. 2011). The study found the fungicide chlorothalonil and the insecticides chlorpyrifos and imidacloprid in bee-collected pollen (Frazier et al. 2011).

_Motivation_  
------------------------------------------------------
Bee colony decline has made headlines in recent news reports. The decrease in bee survival has been linked to a decrease in crop diversity, loss of habitat, poor beekeeping practices, and widespread and intensive use of pesticides such as neonicotinoids. As a group we are interested in trends between pesticide use and bee populations. If the bee population continues to decline, biodiversity of plants across the country will continue to decline, with potentially catastrophic implications to our food supply.

_Intended Final Project_  
------------------------------------------------------

We propose to examine county level data on pesticide use and county level data on bee colonies to see if there are any trends between certain chemical compounds and bee colony decline. We plan to include information on the relationship between bee population over time as well as pesticide use over time controlling for seasonality. Additionally, we will examine bee population in the counties with the highest and lowest pesticide use. Based on these trends, we will investigate pesticides that have stronger associations with bee colony population over time. We aim to identify pesticides that are associated with changes in bee populations, specifically those that might contribute to the recent decline in bee populations nationally. 

_Methods_
------------------------------------------------------

Based on the literature, the following pesticides were selected for analysis in this project:    
------------------------------------------------------
* Neonicotinoids:
Imidacloprid, Thiacloprid, Clothianidin   
* Organophosphates:
Chlorpyrifos, Methyl parathion  
* Fungicide:
Chlorothalonil  
* Other insecticide:
Fipronil  

_Data sources and availability_
------------------------------------------------------
* Pesticide use data was obtained from https://water.usgs.gov/nawqa/pnsp/usage/maps/county-level/

* County-level bee colony data obtained from https://data.world/finley/bee-colony-statistical-data-from-1987-2017 

* State-level bee colony data obtained from  xxxxxxx


_References_
------------------------------------------------------
* Frazier, J., Mullin, C., Frazier, M., & Ashcraft, S. (2011). Pesticides and their involvement in colony collapse disorder. Am Bee J, 151, 779-781. https://bee-health.extension.org/pesticides-and-their-involvement-in-colony-collapse-disorder/

* Sánchez-Bayo, F., Goulson, D., Pennacchio, F., Nazzi, F., Goka, K., & Desneux, N. (2016). Are bee diseases linked to pesticides?—A brief review. Environment international, 89, 7-11.https://www-sciencedirect-com.ezproxy.cul.columbia.edu/science/article/pii/S0160412016300095?via%3Dihub

* G. Di Prisco, V. Cavaliere, D. Annoscia, P. Varricchio, E. Caprio, F. Nazzi, G. Gargiulo, F. Pennacchio
Neonicotinoid clothianidin adversely affects insect immunity and promotes replication of a viral pathogen in honey bees, PNAS, 110 (2013), pp. 18466-18471 van Lexmond, M.B., Bonmatin, JM., Goulson, D. et al. Environ Sci Pollut Res (2015) 22: 1. https://doi.org/10.1007/s11356-014-3220-1

* Zawislak, J., Adamczyk, J., Johnson, D. R., Lorenz, G., Black, J., Hornsby, Q., ... & Joshi, N. (2019). Comprehensive Survey of Area-Wide Agricultural Pesticide Use in Southern United States Row Crops and Potential Impact on Honey Bee Colonies. Insects, 10(9), 280. https://www.mdpi.com/2075-4450/10/9/280/htm

