---
title: "Bee Project Proposal"
author: "Tess Bloomquist, Misbath Daouda, Lizbeth Gomez, Sarah McLarnan, Maya Spaur"
date: "11/6/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Group Members
Sarah McLarnan (smm2316)  
Misbath Daouda (md3851)  
Maya Spaur (mss2284)  
Lizbeth Gomez (lg2982)  
Tess Bloomquist (tb2715)  

### Project Title
Pesticide Use and Bee Colonies in the United States

### Motivation 
Bee colony decline has made headlines in recent news reports. The decrease in bee survival has been linked to a decrease in crop diversity, loss of habitat, poor beekeeping practices, and widespread and intensive use of pesticides such as neonicotinoids. As a group we are interested in trends between pesticide use and bee populations. If the bee population continues to decline, biodiversity of plants across the country will continue to decline, with potentially catastrophic implications to our food crops.

### Intended Final Project 

### Anticipated Data Sources 
- Pesticide use: https://water.usgs.gov/nawqa/pnsp/usage/maps/county-level/
- Bee population: https://data.world/finley/bee-colony-statistical-data-from-1987-2017
- County name and FIPS: https://catalog.data.gov/dataset?tags=county-codes

### Analyses/Visualizations/Coding Challenges 

### Planned Timeline 
