---
title: "Pesticide Change Over the Years"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(tidyverse)

```

County Pesticide Data

```{r read in data}
merged_county_data = read_csv("./data/merged_county_data.csv") %>%
  janitor::clean_names() %>%
  rename(year = year_x)

merged_state_data = read_csv("./data/merged_state_data.csv") %>%
  janitor::clean_names() %>%
  rename(year = year_x)

```


Column {.sidebar}
-----------------------------------------------------------------------

###County Data 

```{r}
compounds = merged_county_data %>% distinct(compound) %>% pull()

# selectInput widget
selectInput(
  "pesticide_choice", 
  label = h3("Select pesticide"),
  choices = compounds, selected = "IMIDACLPROPID")


years = merged_county_data %>% distinct(year) %>% pull()


selectInput(
  "year_choice", 
  label = h3("Choose year"),
  choices = years, selected = "2012")

renderPrint({ 
  input[["compound_choice"]]
})

renderPrint({ 
  input[["year_choice"]]
})
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, eval = FALSE}
renderPlotly({ 
  merged_county_data %>%
  filter(
  compound == input$compound_choice,
  year == input$year_choice) %>%
  mutate(text_label = str_c("Compound: ", compound, '\nYear: ', year)) %>% 
  plot_ly(
    x = ~colony_count, y = ~epest_high_kg, type = "scatter", mode = "markers",
    alpha = 0.5, text = ~text_label)
})

library(maps)
map('state')
cnty.fips <- county.fips$fips[match(map("county", plot=FALSE)$names,
    county.fips$polyname)]

data("merged_county_data")
merged_county_data %>%
  map("state", xlim = range(epest_high_kg$x), ylim = range(epest_high_kg$y))
  
```

Column {.sidebar}
-----------------------------------------------------------------------

###State Data

```{r}
compounds = merged_state_data %>% distinct(compound) %>% pull()


# selectInput widget
selectInput(
  "pesticide_choice", 
  label = h3("Select pesticide"),
  choices = compounds, selected = "IMIDACLPROPID")


years = merged_county_data %>% distinct(year) %>% pull()


selectInput(
  "year_choice", 
  label = h3("Choose year"),
  choices = years, selected = "2012")

renderPrint({ 
  input[["compound_choice"]]
})

renderPrint({ 
  input[["year_choice"]]
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}


```

### Chart C

```{r}

```
