---
title: "Pesticide Change Over the Years"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(tidyverse)
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)

```


#Reading in data

```{r read in data,include=FALSE}
merged_county_data = read_csv("./data/merged_county_data.csv") %>%
  janitor::clean_names() %>%
  rename(year = year_x) %>%
  mutate(
    county = str_to_lower(county)
  )

summary(merged_county_data)

view(merged_county_data)

merged_state_data = read_csv("./data/merged_state_data.csv") %>%
  janitor::clean_names() %>%
  rename(year = year_x)

```

#Reading in other data

```{r, include = FALSE}
pesticides = read_csv("./data/top_pesticides.csv") %>% 
  select(-epest_low_kg)

fips_codes = read_csv("./data/fips_codes.csv")

```


```{r}
usa <- map_data("state")
counties <- map_data("county")

merged_state_data_for_join = 
  merged_state_data %>%
  rename(region = state)

merged_county_data_for_join =
  merged_county_data %>%
  rename(subregion = county)
  

```

```{r}
usa_2 <- merged_state_data_for_join %>%
            left_join(usa, "region")

county_2 <- merged_county_data_for_join %>%
  left_join(counties, "subregion")

head(county_2)
  
```


Column {data-width=650}
-----------------------------------------------------------------------

###County Data 

```{r}

counties_base <- ggplot(data = counties, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")

map_county <- counties_base + theme_nothing() + 
  geom_polygon(data = county_2, aes(fill= epest_high_kg), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_bw()

map_county
  
```

Column  {data-width=350}
-----------------------------------------------------------------------

###State Data

```{r}
usa_base <- ggplot(data = usa, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black")

map <- usa_base + theme_nothing() + 
  geom_polygon(data = usa_2, aes(fill= high), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_bw()

map
view(usa_2)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, eval = FALSE}


library(maps)
map('state')
map('county')
cnty.fips <- county.fips$fips[match(map("county", plot=FALSE)$names,
    county.fips$polyname)]

data("merged_county_data")
#merged_county_data %>%
  map("state", xlim = range(epest_high_kg$x), ylim = range(epest_high_kg$y))

```


