---
title: "selected_maps"
output: html_document
---

```{r setup, include=FALSE}
library(plotly)
library(tidyverse)
library(ggplot2)
library(ggmap)
library(maps)
library(choroplethrMaps)
library(patchwork)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

#Reading in data

```{r read in data,include=FALSE}
merged_county_data = read_csv("./data/merged_county_data.csv") %>%
  janitor::clean_names() %>%
  rename(year = year_x) %>%
  mutate(
    county = str_to_lower(county)
  )

merged_state_data = read_csv("./data/merged_state_data.csv") %>%
  janitor::clean_names() %>%
  rename(year = year_x)

```


```{r, include = FALSE}
state.map <- map_data("state")
counties <- map_data("county")

merged_county_data_for_join =
  merged_county_data %>%
  rename(subregion = county)

county_2 <- merged_county_data_for_join %>%
  left_join(counties, "subregion")

```


#2012 and 2007 data

```{r making each pesticide data file, include=FALSE}

CHLORPYRIFOS =
  county_2 %>%
  filter(compound=="CHLORPYRIFOS")

CLOTHIANIDIN =
  county_2 %>%
  filter(compound=="CLOTHIANIDIN")

IMIDACLOPRID=
  county_2 %>%
  filter(compound=="IMIDACLOPRID")

CHLOROTHALONIL =
  county_2 %>%
  filter(compound=="CHLOROTHALONIL")

FIPRONIL =
  county_2 %>%
  filter(compound=="FIPRONIL")

THIACLOPRID =
  county_2 %>%
  filter(compound=="THIACLOPRID")

```

# **County Level Maps**

*Pesticides*

```{r building base and pesticide maps, include = FALSE}

counties_base <- ggplot(data = counties, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "gray")

map_county <- counties_base + theme_nothing() + 
  geom_polygon(data = county_2, aes(fill= epest_high_kg), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_void() + labs(title= "All Pesticides, All Years, County Level Data", fill = "Estimated Pesticide Use (Kg)") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5))


CHLORPYRIFOS_map <- counties_base + theme_nothing() + 
  geom_polygon(data = CHLORPYRIFOS, aes(fill= epest_high_kg), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_void() + labs(title= "Chlorpyrifos, County Level Data", fill = "Estimated Pesticide Use (Kg)") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + facet_grid(~year)

CLOTHIANIDIN_map <- counties_base + theme_nothing() + 
  geom_polygon(data = CLOTHIANIDIN, aes(fill= epest_high_kg), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_void() + labs(title= "Clothianidin, County Level Data", fill = "Estimated Pesticide Use (Kg)") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + facet_grid(~year)

IMIDACLOPRID_map <- counties_base + theme_nothing() + 
  geom_polygon(data = IMIDACLOPRID, aes(fill= epest_high_kg), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_void() + labs(title= "Imidacloprid, County Level Data", fill = "Estimated Pesticide Use (Kg)") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + facet_grid(~year)

CHLOROTHALONIL_map <- counties_base + theme_nothing() + 
  geom_polygon(data = CHLOROTHALONIL, aes(fill= epest_high_kg), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_void() + labs(title= "Chlorothalonil, County Level Data", fill = "Estimated Pesticide Use (Kg)") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + facet_grid(~year)

FIPRONIL_map <- counties_base + theme_nothing() + 
  geom_polygon(data = FIPRONIL, aes(fill= epest_high_kg), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_void() + labs(title= "Fipronil, County Level Data", fill = "Estimated Pesticide Use (Kg)") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + facet_grid(~year)

THIACLOPRID_map <- counties_base + theme_nothing() + 
  geom_polygon(data = THIACLOPRID, aes(fill= epest_high_kg), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_void() + labs(title= "Thiacloprid, County Level Data", fill = "Estimated Pesticide Use (Kg)") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + facet_grid(~year)
```


```{r printing maps}

CHLOROTHALONIL_map 
CHLORPYRIFOS_map 
CLOTHIANIDIN_map
FIPRONIL_map
IMIDACLOPRID_map
THIACLOPRID_map

```


*All Bees*

```{r, include = FALSE}
map_county_bees <- counties_base + theme_nothing() + 
  geom_polygon(data = county_2, aes(fill= colony_count), color = "white") + geom_polygon(color = "black", fill = NA) +
      theme_void() + labs(title= "All Bees, All Years, County Level Data", fill = "Number of Bee Colonies") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + facet_grid(~year)
```

```{r}
map_county_bees

```

<br>

# **State level maps**

*Pesticides*

```{r state chlorpyrifos, include = FALSE}
state_chlorpyrifos =
  merged_state_data %>%
  mutate(state = str_to_lower(state)) %>%
  rename(region = state) %>%
  filter(compound == "CHLORPYRIFOS") %>%
  filter(year == "2007" | year == "2012")

state_map_chlorpyrifos = left_join(state.map, state_chlorpyrifos, by = "region") 

chlorpyrifos_map_state =
  ggplot(state_map_chlorpyrifos, aes(long, lat, group = group, fill = high)) + geom_polygon(color = "black") + theme_void() + labs(title = "Chlorpyrifos Use", fill = "Estimated Pesticide Use (Kg)") +  coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_gradient(low = "white", high = "red") + facet_grid(~year)

```

```{r state chlorothalonil, include = FALSE}
state_chlorothalonil =
  merged_state_data %>%
  mutate(state = str_to_lower(state)) %>%
  rename(region = state) %>%
  filter(compound == "CHLOROTHALONIL") %>%
  filter(year == "2007" | year == "2012")


state_map_chlorothalonil = left_join(state.map, state_chlorpyrifos, by = "region") 

chlorothalonil_map_state =
  ggplot(state_map_chlorothalonil, aes(long, lat, group = group, fill = high)) + geom_polygon(color = "black") + theme_void() + labs(title = "Chlorothalonil Use", fill = "Estimated Pesticide Use (Kg)") +  coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_gradient(low = "white", high = "red") + facet_grid(~year)

```


```{r state imidacloprid, include = FALSE}
state_imidacloprid =
  merged_state_data %>%
  mutate(state = str_to_lower(state)) %>%
  rename(region = state) %>%
  filter(compound == "IMIDACLOPRID") %>%
  filter(year == "2007" | year == "2012")

state_map_imidacloprid = left_join(state.map, state_chlorpyrifos, by = "region") 

imidacloprid_map_state =
  ggplot(state_map_imidacloprid, aes(long, lat, group = group, fill = high)) + geom_polygon(color = "black") + theme_void() + labs(title = "Imidacloprid Use", fill = "Estimated Pesticide Use (Kg)") +  coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_gradient(low = "white", high = "red") + facet_grid(~year)

```

```{r state thiacloprid, include = FALSE}
state_thiacloprid =
  merged_state_data %>%
  mutate(state = str_to_lower(state)) %>%
  rename(region = state) %>%
  filter(compound == "THIACLOPRID") %>%
  filter(year == "2007" | year == "2012")
  

state_map_thiacloprid = left_join(state.map, state_chlorpyrifos, by = "region") 

thiacloprid_map_state =
  ggplot(state_map_thiacloprid, aes(long, lat, group = group, fill = high)) + geom_polygon(color = "black") + theme_void() + labs(title = "Thiacloprid Use", fill = "Estimated Pesticide Use (Kg)") +  coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_gradient(low = "white", high = "red") + facet_grid(~year)

```



```{r state clothianidin, include = FALSE}
state_clothianidin =
  merged_state_data %>%
  mutate(state = str_to_lower(state)) %>%
  rename(region = state) %>%
  filter(compound == "Clothianidin") %>%
  filter(year == "2007" | year == "2012")

state_map_clothianidin = left_join(state.map, state_chlorpyrifos, by = "region") 

clothianidin_map_state =
  ggplot(state_map_clothianidin, aes(long, lat, group = group, fill = high)) + geom_polygon(color = "black") + theme_void() + labs(title = "Clothianidin Use", fill = "Estimated Pesticide Use (Kg)") +  coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_gradient(low = "white", high = "red") + facet_grid(~year)

```


```{r printing state maps}

chlorothalonil_map_state
chlorpyrifos_map_state
clothianidin_map_state
imidacloprid_map_state
thiacloprid_map_state

```


<br>

*Honey Bees*

```{r state bees, include = FALSE}
merged_state_data = read_csv("./data/merged_state_data.csv")

merged_state_data_map =
  merged_state_data %>%
  mutate(state = str_to_lower(state)) %>%
  rename(region = state) %>%
  rename(year = year.x) %>%
  filter(year == "2007" | year == "2012")


state_map_data = left_join(state.map, merged_state_data_map, by = "region")

honey_bee_colony_map = 
  ggplot(state_map_data, aes(long, lat, group = group, fill = honey_producing_colonies)) + geom_polygon(color = "black") + theme_void() + labs(title = "Honey Producing Colonies 2007", fill = "Honey Producing Colonies") + coord_map(projection = "bonne", lat0 = 50) + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_gradient(low = "white", high = "red") + facet_grid(~year)

```

```{r}

honey_bee_colony_map

```







