---
title: "Pesticide Use and Bee Trends in the US"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(tidyverse)
library(Hmisc)
library(ggmap)
library(maps)
library(choroplethrMaps)


#Adding in pesticide data 
pesticides = read_csv("./data/top_pesticides.csv") %>% 
  mutate(compound = capitalize(tolower(compound))) %>% 
  mutate(state = recode(state_fips, "01" = "AL", "04" = "AZ", "05" = "AR", "06" = "CA", "08" = "CO", "09" = "CT", "10" = "DE", "12" = "FL", "13" = "GA", "16" = "ID", "17" = "IL", "18" = "IN", "19" = "IA", "20" = "KS", "21" = "KY", "22" = "LA", "23" = "ME", "24" = "MD", "25" = "MA", "26" = "MI", "27" = "MN", "28" = "MS", "29" = "MO", "30" = "MT", "31" = "NE", "32" = "NV", "33" = "NH", "34" = "NJ", "35" = "NM", "36" = "NY", "37" = "NC", "38" = "ND", "39" = "OH", "40" = "OK", "41" = "OR", "42" = "PA", "44" = "RI", "45" = "SC", "46" = "SD", "47" = "TN", "48" = "TX", "49" = "UT", "50" = "VT", "51" = "VA", "53" = "WA", "54" = "WV", "55" = "WI", "56" = "WY")) %>%
  select(-epest_low_kg)

#Adding in honey bee data
clean_bee_data = read_csv("./data/clean_bee_data.csv") 

#Adding in bee data 
bee_county = read_csv("./data/bee_county.csv") %>% 
  mutate(state = capitalize(tolower(state))) %>% 
  arrange(-desc(state_ansi))
```

Pesticide Use 
=====================================

Column {.sidebar}
-----------------------------------------------------------------------

```{r, echo=FALSE}
years = pesticides %>% distinct(year) %>% pull()

# selectInput widget for year
selectInput(
  "year_choice", 
  label = h3("Select Year"),
  choices = years, selected = "2004")

states = pesticides %>% distinct(state) %>% pull()

# selectInput widget for state
selectInput(
  "state_choice", 
  label = h3("Select State"),
  choices = states, selected = "AL")


```

Column {.tabset}
-----------------------------------------------------------------------

### Bar Plot

```{r, echo=FALSE}

renderPlotly({
  pesticides %>%
  filter(year == input$year_choice, 
        state == input$state_choice) %>%
  group_by(state_fips, compound) %>%
  summarise(tot_pest_high = sum(epest_high_kg)) %>%
  plot_ly(x = ~compound, y = ~tot_pest_high, color = ~compound, type = "bar") %>%
  layout(xaxis = list(title = 'Pesticide'),
         yaxis = list(title = 'Estimated Use (Kg)'))
  
})
```

All Bee Species
=====================================
  
Column {.sidebar}
-----------------------------------------------------------------------
```{r, echo=FALSE}

state_bee = bee_county %>% distinct(state) %>% pull()

# selectInput widget for year
selectInput(
  "state_choice_bee", 
  label = h3("Select State"),
  choices = state_bee, selected = "Alabama")

```

Column {.tabset}
-----------------------------------------------------------------------

### Trend
  
```{r, echo=FALSE}
renderPlotly({
  
  bee_county %>%
    filter(state == input$state_choice_bee) %>%
    mutate(colony_count = as.numeric(colony_count)) %>%
    drop_na(colony_count) %>%
    group_by(year) %>%
    summarise(n = sum(colony_count)) %>%
    ggplot(aes(x = year, y = n)) + 
    geom_point() + 
    geom_smooth() +
    theme(axis.text.x = element_text(angle = 90)) +
    labs(
      title = "",
      x = "Year",
      y = "Bee Colony Count") + 
    scale_x_continuous(
      breaks = c(2002, 2007, 2012))
  
  
})
```

Honey Bees 
=====================================

Column {.sidebar}
-----------------------------------------------------------------------
```{r, echo=FALSE}

state_honey_bee = clean_bee_data %>% distinct(state) %>% pull()

# selectInput widget for year
selectInput(
  "state_choice_honey_bee", 
  label = h3("Select State"),
  choices = state_honey_bee, selected = "Alabama")

```

Column {.tabset}
-----------------------------------------------------------------------

### Trend

```{r, echo=FALSE}
renderPlotly({
  
clean_bee_data %>%
   filter(state == input$state_choice_honey_bee) %>%
   mutate(year = as.numeric(year)) %>%
   group_by(year) %>%
   summarise(n = sum(honey_producing_colonies)) %>%
   ggplot(aes(x = year, y = n)) + 
   geom_point() + 
   geom_smooth(se = FALSE) +
   theme(axis.text.x = element_text(angle = 90)) +
   labs(
     title = "",
     x = "Year",
     y = "Honey Bee Colony Count") +
   scale_x_continuous(
      breaks = c(2002, 2007, 2012, 2017))

})
```



